[package]
name = "risc0-zkvm"
version = "0.11.1"
edition = "2021"
description = "RISC Zero zero-knowledge VM"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
anyhow = { version = "1.0", default-features = false }
bytemuck = "1.12"
lazy-regex = { version = "2.3", optional = true }
lazy_static = { version = "1.4", features = ["spin_no_std"] }
risc0-zkp = { version = "0.11", path = "../../../zkp/rust", default-features = false }
risc0-zkvm-circuit = { version = "0.11", path = "circuit", default-features = false }
risc0-zkvm-platform = { version = "0.11", path = "platform" }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

[dev-dependencies]
criterion = "0.3"
tempfile = "3.3"

# TODO(nils): Change these arch checks to vendor checks when we have a
# real target triple.
#
# Host dependencies
[target.'cfg(not(target_arch = "riscv32"))'.dependencies]
addr2line = { version = "0.18", optional = true }
ctor = "0.1"
cxx = "1.0"
gimli = { version = "0.26", optional = true }
log = "0.4"
rand = "0.8"
risc0-zkvm-sys = { version = "0.11", path = "../.." }
sha2 = "0.10"
xmas-elf = "0.8"
prost = { version = "0.11", optional = true }

[build-dependencies]
prost-build = { version = "0.11", optional = true }
protobuf-src = { version = "1.1", optional = true }

[target.'cfg(not(target_arch = "riscv32"))'.dev-dependencies]
env_logger = "0.9"
risc0-zkvm-methods = { path = "methods" }
test-log = "0.2"

[features]
circuit = []
default = ["host", "prove", "std", "verify", "profiler"]
doc = ["std"]
cuda = ["risc0-zkp/cuda", "pure-prove"]
opencl = ["risc0-zkp/opencl", "pure-prove"]
host = ["risc0-zkp/host"]
prove = ["circuit", "dep:lazy-regex", "risc0-zkp/prove", "risc0-zkvm-circuit/cpp"]
std = ["risc0-zkp/std", "serde/std"]
verify = ["circuit", "risc0-zkp/verify"]
profiler = ["dep:addr2line", "dep:gimli", "dep:prost", "dep:prost-build", "dep:protobuf-src"]
# Run rust-based prover instead of FFI-based prover.
pure-prove = []

[[bench]]
name = "guest_run"
harness = false

[[example]]
name = "roundtrip"
required-features = ["opencl"]
